default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25

test:
  <<: *default
  database: nonchosbatta_test

development:
  <<: *default
  database: nonchosbatta_development
  username: nonchosbatta
  password:
  host: localhost
  port: 5432

staging:
  <<: *default
  database: nonchosbatta_staging
  username: deployer
  password: <%= ENV['NONCHOSBATTA_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: nonchosbatta_production
  username: deployer
  password: <%= ENV['NONCHOSBATTA_DATABASE_PASSWORD'] %>
