default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25

test:
  <<: *default
  database: svogliato_test

development:
  <<: *default
  database: svogliato_development
  username: svogliato
  password:
  host: localhost
  port: 5432

staging:
  <<: *default
  database: svogliato_staging
  username: deployer
  password: <%= ENV['SVOGLIATO_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: svogliato_production
  username: deployer
  password: <%= ENV['SVOGLIATO_DATABASE_PASSWORD'] %>
